export enum ExpressionType {
  ARRAY = "ARRAY",
  BIGDECIMAL = "BIGDECIMAL",
  BIGINT = "BIGINT",
  BIGSERIAL = "BIGSERIAL",
  BINARY = "BINARY",
  BIT = "BIT",
  BOOLEAN = "BOOLEAN",
  CHAR = "CHAR",
  DATE = "DATE",
  DATETIME = "DATETIME",
  DATETIME64 = "DATETIME64",
  ENUM = "ENUM",
  INT4RANGE = "INT4RANGE",
  INT4MULTIRANGE = "INT4MULTIRANGE",
  INT8RANGE = "INT8RANGE",
  INT8MULTIRANGE = "INT8MULTIRANGE",
  NUMRANGE = "NUMRANGE",
  NUMMULTIRANGE = "NUMMULTIRANGE",
  TSRANGE = "TSRANGE",
  TSMULTIRANGE = "TSMULTIRANGE",
  TSTZRANGE = "TSTZRANGE",
  TSTZMULTIRANGE = "TSTZMULTIRANGE",
  DATERANGE = "DATERANGE",
  DATEMULTIRANGE = "DATEMULTIRANGE",
  DECIMAL = "DECIMAL",
  DOUBLE = "DOUBLE",
  FLOAT = "FLOAT",
  GEOGRAPHY = "GEOGRAPHY",
  GEOMETRY = "GEOMETRY",
  HLLSKETCH = "HLLSKETCH",
  HSTORE = "HSTORE",
  IMAGE = "IMAGE",
  INET = "INET",
  INT = "INT",
  INT128 = "INT128",
  INT256 = "INT256",
  INTERVAL = "INTERVAL",
  JSON = "JSON",
  JSONB = "JSONB",
  LONGBLOB = "LONGBLOB",
  LONGTEXT = "LONGTEXT",
  MAP = "MAP",
  MEDIUMBLOB = "MEDIUMBLOB",
  MEDIUMTEXT = "MEDIUMTEXT",
  MONEY = "MONEY",
  NCHAR = "NCHAR",
  NULL = "NULL",
  NULLABLE = "NULLABLE",
  NVARCHAR = "NVARCHAR",
  OBJECT = "OBJECT",
  ROWVERSION = "ROWVERSION",
  SERIAL = "SERIAL",
  SET = "SET",
  SMALLINT = "SMALLINT",
  SMALLMONEY = "SMALLMONEY",
  SMALLSERIAL = "SMALLSERIAL",
  STRUCT = "STRUCT",
  SUPER = "SUPER",
  TEXT = "TEXT",
  TIME = "TIME",
  TIMESTAMP = "TIMESTAMP",
  TIMESTAMPTZ = "TIMESTAMPTZ",
  TIMESTAMPLTZ = "TIMESTAMPLTZ",
  TINYINT = "TINYINT",
  UBIGINT = "UBIGINT",
  UINT = "UINT",
  USMALLINT = "USMALLINT",
  UTINYINT = "UTINYINT",
  UNKNOWN = "UNKNOWN",  // Sentinel value, useful for type annotation
  UINT128 = "UINT128",
  UINT256 = "UINT256",
  UNIQUEIDENTIFIER = "UNIQUEIDENTIFIER",
  USERDEFINED = "USER-DEFINED",
  UUID = "UUID",
  VARBINARY = "VARBINARY",
  VARCHAR = "VARCHAR",
  VARIANT = "VARIANT",
  XML = "XML",
}

export const TextTypes = new Set([
  ExpressionType.CHAR,
  ExpressionType.NCHAR,
  ExpressionType.VARCHAR,
  ExpressionType.NVARCHAR,
  ExpressionType.TEXT,
]);

export const IntegerTypes = new Set([
  ExpressionType.INT,
  ExpressionType.TINYINT,
  ExpressionType.SMALLINT,
  ExpressionType.BIGINT,
  ExpressionType.INT128,
  ExpressionType.INT256,
]);

export const FloatTypes = new Set([
  ExpressionType.FLOAT,
  ExpressionType.DOUBLE,
]);

export const NumericTypes = new Set([
  ...FloatTypes,
  ...IntegerTypes,
])

export const TemporalTypes = new Set([
  ExpressionType.TIME,
  ExpressionType.TIMESTAMP,
  ExpressionType.TIMESTAMPTZ,
  ExpressionType.TIMESTAMPLTZ,
  ExpressionType.DATE,
  ExpressionType.DATETIME,
  ExpressionType.DATETIME64,
]);

export const MetaTypes = new Set(["UNKNOWN", "NULL"]);
